
# Setup Dependabot for the package dependecies secuites and vulnerabilities. 
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`. Same for the package.json)
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "github actions: "
      prefix: "github actions"


  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # For ciscodesignsystems, Ignore updates 
      - dependency-name: "@ciscodesignsystems*"
      # For okta packages, Ignore updates 
      - dependency-name: "@okta*"
    commit-message:
      # Prefix all commit messages with "yarn: "
      prefix: "yarn"
       # list of updated dependencies
      include: "scope"

