name: Secret scanning

on:
  workflow_dispatch:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: 'Add path prefix in .gitleaksignore'
        run: |
          grep -n 'Include historical files' .gitleaksignore | `# get separator/separator line` \
          cut -f1 -d: | `# get the line number only` \
          xargs -I CUTLINE_LINE_NUMBER `# define variable to use as dynamic line number in range` \
          awk 'FNR>=0 && FNR<=CUTLINE_LINE_NUMBER-2,/^/{sub(//, "/github/workspace/")} 1' .gitleaksignore > .gitleaksignore.new && `# replace lines in first section` \
          mv .gitleaksignore.new .gitleaksignore

      - name: 'Print the .gitleaksignore file for debugging purposes'
        run: cat .gitleaksignore

      - name: 'Run Gitleaks'
        id: gitleaks
        uses: DariuszPorowski/github-action-gitleaks@5c3e70f794d4c928460daf621eff608f477c2510 # pin to v2.0.9 commit
        with:
          config: 'gitleaks.toml'
          fail: true
          no_git: true

      - name: 'Get the output from the gitleaks step'
        run: |
          echo "exitcode: ${{ steps.gitleaks.outputs.exitcode }}"
          echo "result: ${{ steps.gitleaks.outputs.result }}"
          echo "output: ${{ steps.gitleaks.outputs.output }}"
          echo "command: ${{ steps.gitleaks.outputs.command }}"
          echo "report: ${{ steps.gitleaks.outputs.report }}"
